DROP TRIGGER IMS_ADDRESS_TRG1; 
DROP TRIGGER IMS_CATEGORY_TRG;
DROP TRIGGER IMS_ADDRESS_TRG;
DELETE TRIGGER IMS_SUPPLIER_TRG;

CREATE SEQUENCE new_address_counter
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE OR REPLACE TRIGGER insert_address_trigger
BEFORE INSERT ON IMS_ADDRESS
FOR EACH ROW
BEGIN
 :NEW.A_ID := new_address_counter.nextval;
END;
/