--------------------------------------------------------
--  File created - Friday-September-16-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IMS_ADDRESS
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_ADDRESS" 
   (	"A_STREET" VARCHAR2(4000 BYTE), 
	"A_CITY" VARCHAR2(4000 BYTE), 
	"A_STATE" VARCHAR2(4000 BYTE), 
	"A_ZIP" VARCHAR2(4000 BYTE), 
	"A_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_CATEGORY
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_CATEGORY" 
   (	"C_ID" NUMBER, 
	"C_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_PO_LINE
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_PO_LINE" 
   (	"POL_ID" NUMBER, 
	"POL_PO" NUMBER, 
	"POL_PRODUCT" NUMBER, 
	"POL_QUANTITY" NUMBER, 
	"POL_COST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_PRODUCT
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_PRODUCT" 
   (	"P_ID" VARCHAR2(20 BYTE), 
	"P_NAME" VARCHAR2(20 BYTE), 
	"P_SUPPLIER_PRICE" VARCHAR2(20 BYTE), 
	"P_RETAILER_PRICE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_PRODUCT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_PRODUCT_CATEGORY" 
   (	"C_ID" VARCHAR2(20 BYTE), 
	"C_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_PURCHASE_ORDER
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_PURCHASE_ORDER" 
   (	"PO_ID" NUMBER, 
	"PO_TS" TIMESTAMP (6), 
	"PO_SUPPLIER" NUMBER, 
	"PO_RETAILER" NUMBER, 
	"PO_COST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_RETAILER
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_RETAILER" 
   (	"R_ID" NUMBER, 
	"R_NAME" VARCHAR2(4000 BYTE), 
	"R_ADDRESS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_RETAILER_INVENTORY
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_RETAILER_INVENTORY" 
   (	"R_ID" NUMBER, 
	"RI_RETAILER" NUMBER, 
	"RI_PRODUCT" VARCHAR2(20 BYTE), 
	"RI_PRODUCT_QUALITY" VARCHAR2(20 BYTE), 
	"RI_PRODUCT_MIN_AMNT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_RETAILER_SALE
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_RETAILER_SALE" 
   (	"RS_ID" NUMBER, 
	"RS_RETAILER" NUMBER, 
	"RS_PRODUCT" NUMBER, 
	"RS_PRODUCT_QUANTITY" NUMBER, 
	"RS_COST" NUMBER, 
	"RS_TS" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMS_SUPPLIER
--------------------------------------------------------

  CREATE TABLE "IMS"."IMS_SUPPLIER" 
   (	"S_NAME" VARCHAR2(4000 BYTE), 
	"S_ADDRESS" NUMBER, 
	"S_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_CATEGORY_PK" ON "IMS"."IMS_CATEGORY" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_CATEGORY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_CATEGORY_UK1" ON "IMS"."IMS_CATEGORY" ("C_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_PO_LINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_PO_LINE_PK" ON "IMS"."IMS_PO_LINE" ("POL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_PRODUCT_PK" ON "IMS"."IMS_PRODUCT" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_PRODUCT_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_PRODUCT_CATEGORY_PK" ON "IMS"."IMS_PRODUCT_CATEGORY" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_PURCHASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_PURCHASE_ORDER_PK" ON "IMS"."IMS_PURCHASE_ORDER" ("PO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_RETAILER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_RETAILER_PK" ON "IMS"."IMS_RETAILER" ("R_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_RETAILER_INVENTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_RETAILER_INVENTORY_PK" ON "IMS"."IMS_RETAILER_INVENTORY" ("R_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_RETAILER_SALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_RETAILER_SALE_PK" ON "IMS"."IMS_RETAILER_SALE" ("RS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_SUPPLIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_SUPPLIER_PK" ON "IMS"."IMS_SUPPLIER" ("S_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMS_SUPPLIER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMS"."IMS_SUPPLIER_UK1" ON "IMS"."IMS_SUPPLIER" ("S_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table IMS_CATEGORY
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_CATEGORY" ADD CONSTRAINT "IMS_CATEGORY_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_CATEGORY" ADD CONSTRAINT "IMS_CATEGORY_UK1" UNIQUE ("C_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_CATEGORY" MODIFY ("C_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_PO_LINE
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_PO_LINE" ADD CONSTRAINT "IMS_PO_LINE_PK" PRIMARY KEY ("POL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_PO_LINE" MODIFY ("POL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_PRODUCT" ADD CONSTRAINT "IMS_PRODUCT_PK" PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_PRODUCT" MODIFY ("P_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_PRODUCT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_PRODUCT_CATEGORY" ADD CONSTRAINT "IMS_PRODUCT_CATEGORY_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_PRODUCT_CATEGORY" MODIFY ("C_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_PURCHASE_ORDER" ADD CONSTRAINT "IMS_PURCHASE_ORDER_PK" PRIMARY KEY ("PO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_PURCHASE_ORDER" MODIFY ("PO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_RETAILER
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_RETAILER" ADD CONSTRAINT "IMS_RETAILER_PK" PRIMARY KEY ("R_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_RETAILER" MODIFY ("R_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_RETAILER_INVENTORY
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_RETAILER_INVENTORY" ADD CONSTRAINT "IMS_RETAILER_INVENTORY_PK" PRIMARY KEY ("R_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_RETAILER_INVENTORY" MODIFY ("R_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_RETAILER_SALE
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_RETAILER_SALE" ADD CONSTRAINT "IMS_RETAILER_SALE_PK" PRIMARY KEY ("RS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_RETAILER_SALE" MODIFY ("RS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMS_SUPPLIER
--------------------------------------------------------

  ALTER TABLE "IMS"."IMS_SUPPLIER" ADD CONSTRAINT "IMS_SUPPLIER_UK1" UNIQUE ("S_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_SUPPLIER" ADD CONSTRAINT "IMS_SUPPLIER_PK" PRIMARY KEY ("S_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."IMS_SUPPLIER" MODIFY ("S_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger IMS_ADDRESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IMS"."IMS_ADDRESS_TRG" 
BEFORE INSERT ON IMS_ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IMS"."IMS_ADDRESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IMS_ADDRESS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IMS"."IMS_ADDRESS_TRG1" 
BEFORE INSERT ON IMS_ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.A_ID IS NULL THEN
      SELECT IMS_ADDRESS_SEQ1.NEXTVAL INTO :NEW.A_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IMS"."IMS_ADDRESS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IMS_CATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IMS"."IMS_CATEGORY_TRG" 
BEFORE INSERT ON IMS_CATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.C_ID IS NULL THEN
      SELECT IMS_CATEGORY_SEQ.NEXTVAL INTO :NEW.C_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IMS"."IMS_CATEGORY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IMS_SUPPLIER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IMS"."IMS_SUPPLIER_TRG" 
BEFORE INSERT ON IMS_SUPPLIER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IMS"."IMS_SUPPLIER_TRG" ENABLE;
